# Generated by Django 4.1 on 2023-05-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalAssociationModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield', max_length=128, unique=True)),
                ('address', models.CharField(max_length=512)),
                ('person', models.CharField(max_length=256)),
                ('telephone', models.CharField(blank=True, max_length=16, null=True)),
                ('web_site', models.CharField(blank=True, max_length=128, null=True)),
                ('e_mail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Regional Association',
                'verbose_name_plural': 'Regional Associations',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Topic_Module',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('module', models.CharField(blank=True, max_length=64, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='web_app.topicmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
                ('teachers', models.ManyToManyField(related_name='events', to='web_app.teachermodel')),
                ('topic_modules', models.ManyToManyField(to='web_app.topic_module')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
