# Generated by Django 4.2 on 2023-04-30 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Topic_Module',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('module', models.CharField(blank=True, max_length=64, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.topicmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('city', models.CharField(max_length=64)),
                ('teachers', models.ManyToManyField(related_name='events', to='web_app.teachermodel')),
                ('topic_modules', models.ManyToManyField(to='web_app.topic_module')),
            ],
        ),
    ]
