# Generated by Django 4.1 on 2023-05-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalassociationmodel',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=128, null=True, unique=True),
        ),
    ]
