# Generated by Django 4.2 on 2023-04-30 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_teachermodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicmodel',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterField(
            model_name='topic_module',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='web_app.topicmodel'),
        ),
    ]
