# Generated by Django 4.1 on 2023-06-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_eventmodel_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionalassociationmodel',
            name='slug',
        ),
    ]
