# Generated by Django 4.2 on 2023-04-30 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_topicmodel_options_alter_topic_module_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
