# Generated by Django 4.2 on 2023-04-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('web_app', '0005_alter_eventmodel_options_alter_eventmodel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country'),
        ),
    ]
