# Generated by Django 4.2 on 2023-04-30 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('web_app', '0006_eventmodel_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='city',
        ),
        migrations.AddField(
            model_name='topic_module',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
    ]
