# Generated by Django 4.2 on 2023-04-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_remove_eventmodel_city_topic_module_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='country',
        ),
    ]
